media:
  - name: images
    label: Images
    input: src/assets/images/content
    output: /assets/images/content
    rename: safe
    categories: [image]
    commit:
      templates:
        create: "chore(Images): add {filename}"
        update: "chore(Images): update {filename}"
        delete: "chore(Images): remove {filename}"
        rename: "chore(Images): rename {oldFilename} -> {newFilename}"
  - name: docs
    label: Documents
    input: src/assets/documents
    output: /assets/documents
    categories: [document]
    commit:
      templates:
        create: "chore(Documents): add {filename}"
        update: "chore(Documents): update {filename}"
        delete: "chore(Documents): remove {filename}"
        rename: "chore(Documents): rename {oldFilename} -> {newFilename}"
content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    fields:
      - name: draft
        type: boolean
        default: false
        label: Draft
      - name: title
        type: string
        label: Title
      - name: description
        type: text
        label: Description
      - name: date
        type: date
        label: Last Updated
        default: ""
        options:
          format: yyyy-MM-dd
      - name: coverImage
        label: Cover Image
        type: image
        options:
          categories: [image]
      - name: tags
        label: Tags 
        type: string
        list: true 
      - name: body
        type: rich-text
        options:
          format: markdown
actions:
  - name: deploy-site
    label: Deploy site
    workflow: pages-cms-action.yml